### ISSUE TITLE
No results when using international release of SNOMED CT

### ISSUE THREAD

**Issue by waydes** [IHTSDO/snomed-owl-toolkit#18]
I am attempting to understand the reasoner and following the documentation and running the reasoner with the following command:
java -Xmx3800m -Xms3800m  -XX:+UseParallelGC  -XX:ParallelGCThreads=2 -jar snomed-owl-toolkit-2.0.1-executable.jar -classify -rf2-snapshot-archives SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z.zip

I modified the international release file, so it only contains the snapshot folder.  The reasoner seems to run without error but the resulting zip file contains the two files with only a header and no results.  I expected the reasoner would used the stated relationship file in the release to create the inferred relations in the resulting zip file.  I am attaching a log file of the output in the terminal and the zip file created. 

I am using Ubuntu 18.04 and java version:
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
 
I am stumped as to why  I can not get the expected results.  Any comments are appreciated.

[classification-results-2018-11-04_20-30-28.zip](https://github.com/IHTSDO/snomed-owl-toolkit/files/2546731/classification-results-2018-11-04_20-30-28.zip)
[logfile.txt](https://github.com/IHTSDO/snomed-owl-toolkit/files/2546732/logfile.txt)

**Comment by riannella** [comment]
I have a similar problem...I am using the latest SNOMED-CT-AU snapshot, and all that is returned (in the OWL file) are the annotations.

**Comment by kaicode** [comment]
Hi @waydes,

There is no need to remove the delta and full files from the international release archive. The toolkit will select the snapshot entries from any archives given in the snapshot parameter.

Your log file looks good. Things worked as they should during that run.

The results files contain no rows of data because the stated relationship snapshot has been used to classify snomed then the inferred relationship snapshot has been used to diff against this. When no new inferences and no redundant relationships are found the output relationship delta will be empty. When no equivalent concepts are found the output equivalent concept reference set will also be empty.

If you want to see some results in the output you could provide an archive with some new concepts or relationships using the -rf2-authoring-delta-archive parameter. Alternatively you _could_ modify the snapshot entries within the international archive and add or remove some relationships or OWL axioms.

I hope that help!
Kind regards,
Kai
