### ISSUE TITLE
Version ambiguity

### ISSUE THREAD

**Issue by rwynne** [IHTSDO/snomed-owl-toolkit#29]
The 'version' is represented as the date and time the conversion is run.

Would it be possible to comment the version/release of SNOMED in the OWL (e.g., January 2019 International, March 2019 US Edition, and so on)?

In \Full\Terminology, I think this could be represented from a .txt file name *_Full_VVV_YYYYMMDD.txt ?

**Comment by kaicode** [comment]
Hi @rwynne 

It sounds like you are using the "Snomed RF2 to OWL File Conversion" function.

Yes, the ontology version can be set using the `-version` parameter.

From README:
```
Optional parameters for OWL conversion:
...
 -version <version>                     (Optional) Date for the ontology version e.g. 20180731.
                                        Defaults to today's date.
```
We do not set this automatically because there are many scenarios for this function including converting work in progress.

I hope this helps.

Kind regards,
Kai
