### ISSUE TITLE
Classification process

### ISSUE THREAD

**Issue by Turiath** [IHTSDO/snomed-owl-toolkit#33]
Hi, 

I've tried to run the taxonomy classification with the last international version as follows:

java -jar snomed-owl-toolkit-2.8.0-executable.jar  -classify -rf2-snapshot-archives  SnomedCT_International_Edition.zip

Aunque se crea el archivo comprimido classification-results-2019-12-16_14-17-29.zip, todos los archivos contenidos están vacíos.
* der2_sRefset_EquivalentConceptSimpleMapDelta_Classification_20191216.txt
* sct2_Relationship_Delta_Classification_20191216.txt

Am I doing anything wrong?

**Comment by CoderMChu** [comment]
Hi @Turiath,
Yes the empty results are expected as you are classifying the international release itself without any  changes. You can use -rf2-authoring-delta-archive flag if you have any concept modelling changes. Or adding the extension release snapshot file as part of of -rf2-snapshot-archives parameter.

Hope this helps. 

Thanks

Michael

**Comment by kaicode** [comment]
Hi @Turiath,
In addition to Michael's comment - we classify the International Edition as part of the release process and include the inferred relationships in the publication. The concepts from `sct2_Concept_Snapshot_INT_20190731.txt` and axioms from `sct2_sRefset_OWLExpressionSnapshot_INT_20190731.txt` are used to produce an OWL representation of SNOMED CT. The OWL Toolkit then produces a set of inferred relationships which are published in `sct2_Relationship_Snapshot_INT_20190731.txt`.  If you classify the release and get no results that means we have done our job properly 😄. Most people just want to be able to use the inferred relationships file without having to do anything.

To see the SNOMED OWL Toolkit do something you could either remove some rows from the inferred relationship snapshot file or add some rows to a delta RF2 zip file.

Reading the unit tests are probably a good way to understand the expected behaviour of this project, for example [SimpleExtensionClassificationIntegrationTest.java](https://github.com/IHTSDO/snomed-owl-toolkit/blob/master/src/test/java/org/snomed/otf/owltoolkit/service/classification/SimpleExtensionClassificationIntegrationTest.java).

Kind regards,
Kai
