### ISSUE TITLE
Failed to build existing terminology - BOM marker in UTF-8 files not supported.

### ISSUE THREAD

**Issue by trudiger** [IHTSDO/snomed-owl-toolkit#41]
Dear programmers,

I am getting an error failed to build existing terminology . . .
Caused by ... : 'id' not found as first value in tab separated first line of sct_Concept_Delta_Int_20200309.txt

The first lines of the extracted file in C:\Users\thoma\AppData\Local\Temp\temp-rf2-unzip3860120724017919193/sct2_Concept_Delta_INT_20200309.txt
are 

id	effectivetime	active	moduleid	definitionstatusid
100000011000232107	20190714	1	100000001000232109	900000000000074008
100000021000232102	20190517	1	100000001000232109	900000000000074008
100000341000232108	20190517	1	100000001000232109	900000000000074008
100000371000232103	20190517	1	100000001000232109	900000000000074008

file attached [sct2_Concept_Delta_INT_20200309.txt](https://github.com/IHTSDO/snomed-owl-toolkit/files/4829056/sct2_Concept_Delta_INT_20200309.txt)

What am I doing wrong when exporting the file?

Your help is very much appreaciated.
Thank you 
Thomas

**Comment by kaicode** [comment]
Hi @trudiger, thanks for reaching out.

Yes, the concept file looks fine. It looks like you are working with an extension to and attempting to either classify it or convert it to an OWL ontology file. Could you share the full command you are running on the command line please? 

Kind regards,
Kai Kewley

**Comment by trudiger** [comment]
Sorry, I was not able to respond earlier:

java -Xms4g -jar snomed-owl-toolkit-2.9.0-executable.jar -classify -rf2-snapshot-archives "C:\Users\thoma\Documents\PuffinPathology\Classifier\TR_Delta\SnomedCT_InternationalRF2_PRODUCTION_20200309T120000Z.zip" -rf2-authoring-delta-archive "C:\Users\thoma\Documents\PuffinPathology\Classifier\TR_Delta\SnomedCT_InternationalRF2_PRODUCTION_20200309T120000Z.zip"

I have replaced the concept and delta files in the archive.

Thank you very much 

Thomas

**Comment by trudiger** [comment]
Hi @kaicode,

I have run the classification again and exported the program output: maybe that helps?
[OUTPUT.txt](https://github.com/IHTSDO/snomed-owl-toolkit/files/4834836/OUTPUT.txt).
If you need me to upload anything else, please feel free to reach out.
Thanks Thomas

**Comment by kaicode** [comment]
@trudiger there are some extra bytes at the start of your file are confusing the SNOMED OWL Toolkit.

The expected format of a concept RF2 file has the `i` character at the very start of the file like this:
<img width="981" alt="Screenshot 2020-06-26 at 09 51 35" src="https://user-images.githubusercontent.com/2010517/85839540-f020a180-b792-11ea-9180-72ea25bb7232.png">

The `sct2_Concept_Delta_INT_20200309.txt` file you provided has other bytes before the `i` character as can be seen on this [online hex viewer](https://www.onlinehexeditor.com/).
<img width="978" alt="Screenshot 2020-06-26 at 09 51 24" src="https://user-images.githubusercontent.com/2010517/85839781-4ee61b00-b793-11ea-8834-6afb924cf561.png">

Searching online this may be a UTF-8 Byte Order Mark which may be valid markup but our tooling is not able to recognise this. I also noticed that the headings are all lower case rather than camelCase, although this should not affect loading.

As a workaround you could take the first line of the concept file in the snapshot and paste it over the first line of the concept file in the delta zip. If this works that would confirm the issue.

I've not come across this issue before. I think you are likely to encounter this issue again if you load the delta archive into other SNOMED CT tools. Would it be possible to have the format changed in the tooling which produced the delta files?

Kind regards,
Kai

**Comment by trudiger** [comment]
Dear Kai,

thank you very much for your guidance.

I am exporting these files myself from an MSSQL database via a C# stringbuilder.

Over the weekend, I will look into this and try to confirm your suggestion, so it should be possible to fix the issue. I think, UTF-8 will not be necessary for these files.

I will respond again when I know more.

Thank you very much, indeed.
Yours
Thomas

**Comment by kaicode** [comment]
Great news that you have the capability to update the code which creates your files.

UTF-8 is part of the RF2 standard, I would recommend continuing to use that. It's just the BOM mark which is not expected. I have no experience writing C# but this article looks relevant our situation - https://stackoverflow.com/questions/2502990/create-text-file-without-bom

Best of luck!
Kai

**Comment by trudiger** [comment]
Dear Kai,

it all worked as you suggested!
Thank you very much.
Thomas

**Comment by kaicode** [comment]
Great news, thanks @trudiger.
