### ISSUE TITLE
Not all SNOMED attributes are represented as OWL properties

### ISSUE THREAD

**Issue by bsara** [IHTSDO/snomed-owl-toolkit#51]
It seems that all attributes that are children of [`Concept model object attribute`](http://snomed.info/id/762705008) are correctly converted to be OWL properties. However, all other attributes are only created as OWL classes. I would expect that at least everything that is a subclass/sub-property/sub-attribute of one of the subclasses of [`Attribute`](http://snomed.info/id/246061005) would be an OWL property of some kind after conversion is complete _(including [`Is a`](http://snomed.info/id/116680003), which is a direct child of `Attribute`, but doesn't have any children itself and seems like it should be a property...that, or a sub-property of either `rdf:type` or `rdfs:subClassOf`)_.

_(The same could probably be argued for everything under [`Link assertion`](http://snomed.info/id/416698001) as well.)_

**Comment by kaicode** [comment]
Hi @bsara, thanks for your question.
Yes, only the children of `762705008 |Concept model object attribute (attribute)|` are converted to `ObjectProperty` in OWL. This is because other descendants of `246061005 |Attribute (attribute)|` are not permitted to be used as attributes of a concept model:
- `410663007 |Concept history attribute (attribute)|`
  - Used within historical association reference sets (`900000000000522004 |Historical association reference set (foundation metadata concept)|`)
- `116680003 |Is a (attribute)|`
  - OWL `SubClassOf` / `EquivalentClasses`
- `408739003 |Unapproved attribute (attribute)|`
  - Not permitted in the concept model, these are historical concepts.

More information is available on the permitted attributes used within concepts in the Machine Readable Concept Model (MRCM), See [technical documentation](http://snomed.org/mrcm) and [MRCM Browser](https://browser.ihtsdotools.org/mrcm).

Please note that the July 2021 International release of SNOMED CT will introduce descendants of `762706009 |Concept model data attribute (attribute)|`. These will be converted to `DataProperty` and used in `DataHasValue` fragments.

**Comment by bsara** [comment]
thanks again for your quick responses and thorough explanations!
