### ISSUE TITLE
Converting SNOMED CT to RDF for GraphDB import

### ISSUE THREAD

**Issue by TereLaguinge** [IHTSDO/snomed-owl-toolkit#64]
Hi!
Hope you're well! I tried running the tool, I've downloaded SNOMED CT file from here: 
https://www.nlm.nih.gov/healthit/snomedct/international.html
I tried converting it to owl, but I got this error: "no stated relationships or axions were found, an ontology can't be produced"
Do you know why that can be or what can I do about it?
Thanks a lot For your help!

**Comment by TereLaguinge** [comment]
I ran it like this:
java -Xms1000M -jar snomed-owl-toolkit-3.0.6-executable.jar -rf2-to-owl -rf2-snapshot-archives SnomedCT_InternationalRF2.zip

And get this error:

<img width="895" alt="image" src="https://user-images.githubusercontent.com/69465938/160944216-d3135168-f352-4e31-ae96-8e8ae2aedbc4.png">

**Comment by TereLaguinge** [comment]
Thanks a lot Kai! It worked

**Comment by TereLaguinge** [comment]
Hi Kai! I'm trying to import the ontology to GraphDB, however when I try importing it in the owl format (output of the tool), I get this error: 
![image](https://user-images.githubusercontent.com/69465938/161333739-86311b8c-a706-4552-9f3a-615da0c3688d.png)

It seems to be because it's not in xml format. Do you know if there's a way yo convert the file to owl/xml format, is there any option in the program that I could change to do that conversion?

Thanks a lot for your help!!

**Comment by kaicode** [comment]
Hi @TereLaguinge,
This tool produces the OWL file in functional syntax, not RDF.

There is a converter here that says it can take functional syntax and output RDF/XML but I have not tried it:
http://mowl-power.cs.man.ac.uk:8080/converter/

**Comment by kaicode** [comment]
Do let us know if that works for you, it might be helpful to provide a link to that tool in the readme so other people can find it.

**Comment by kaicode** [comment]
@TereLaguinge I found that the previously mentioned web page conversion tool is not practical because the ontology is too big to be pasted into a text box.

However, I found that [Protégé](https://protege.stanford.edu/) can be used to convert SNOMED CT from OWL Function Syntax into a many other formats! By selecting `File` > `Save as...`

<img width="734" alt="Screenshot 2022-04-04 at 21 38 27" src="https://user-images.githubusercontent.com/2010517/161628033-1ee84d8e-e947-42cf-9825-33d79059430d.png">

**Comment by kaicode** [comment]
I have just successfully imported SNOMED CT into GraphDB.
Steps:
- Convert the SNOMED CT RF2 release using the SNOMED OWL Toolkit to the OWL file (has Functional Syntax)
- Open the OWL file in [Protégé](https://protege.stanford.edu/) then Save as "RDF/XML Syntax"
- Zip the RDF file (reduces the size from ~400M to ~20M)
- Increase the memory of GraphDB from the default 1g to 6g in the `GraphDB Free.cfg` config file by changing `-Xms1g` to `-Xms6g`
- Import into GraphDB - this took around 6 minutes on Macbook Pro M1.
<img width="712" alt="Screenshot 2022-04-05 at 09 16 31" src="https://user-images.githubusercontent.com/2010517/161712670-433c7eed-ee17-43ba-8d21-dd727b253bd4.png">

**Comment by TereLaguinge** [comment]
Thanks a lot Kai!! Really helped!!

**Comment by TereLaguinge** [comment]
Hi @kaicode! I followed those steps and instructions that you listed but when I open the owl file in protege I'm just able to see this relations:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/69465938/162439166-41673d05-a028-4b09-8612-5b9b2cf0c016.png">

However, when comparing that to the ontology of SNOMED in bioportal: https://bioportal.bioontology.org/ontologies/SNOMEDCT

<img width="624" alt="image" src="https://user-images.githubusercontent.com/69465938/162441788-60e3e949-7604-4ffd-b580-b3eeaa9f568a.png">

I have other predicates like Has associated morphology or Has finding site that do not appear in the owl file. 

They seem to be here:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/69465938/162442032-726622d0-b0d2-4f65-a8b0-b25bae62d66c.png">

But they don´t seem to be recognized and when importing them in GraphDB, I just see the predicates: rdfs:label and skos:prefLabel, do you know how can I obtain them, if there's a way of obtaining them as triples?

Thanks in advance for your help!

**Comment by kaicode** [comment]
I am not familiar with GraphDB. I checked the RDF file that Protégé creates from the SNOMED CT ontology and it looks like all the triple information is included. 

For example, for the `Abdominal aortic aneurysm without rupture (disorder)` concept the following RDF was created:
```
    <!-- http://snomed.info/id/75878002 -->

    <owl:Class rdf:about="http://snomed.info/id/75878002">
        <rdfs:subClassOf>
            <owl:Class>
                <owl:intersectionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://snomed.info/id/64572001"/>
                    <owl:Restriction>
                        <owl:onProperty rdf:resource="http://snomed.info/id/609096000"/>
                        <owl:someValuesFrom>
                            <owl:Class>
                                <owl:intersectionOf rdf:parseType="Collection">
                                    <owl:Restriction>
                                        <owl:onProperty rdf:resource="http://snomed.info/id/116676008"/>
                                        <owl:someValuesFrom rdf:resource="http://snomed.info/id/85659009"/>
                                    </owl:Restriction>
                                    <owl:Restriction>
                                        <owl:onProperty rdf:resource="http://snomed.info/id/363698007"/>
                                        <owl:someValuesFrom rdf:resource="http://snomed.info/id/7832008"/>
                                    </owl:Restriction>
                                </owl:intersectionOf>
                            </owl:Class>
                        </owl:someValuesFrom>
                    </owl:Restriction>
                </owl:intersectionOf>
            </owl:Class>
        </rdfs:subClassOf>
        <rdfs:label xml:lang="en">Abdominal aortic aneurysm without rupture (disorder)</rdfs:label>
        <skos:prefLabel xml:lang="en">Abdominal aortic aneurysm without rupture</skos:prefLabel>
    </owl:Class>
```
However in my instance of GraphDB the visual graph shows that concept is not related to anything:
<img width="325" alt="Screenshot 2022-04-11 at 14 17 33" src="https://user-images.githubusercontent.com/2010517/162747773-96de2227-a97f-41b9-99ae-f131be49b48f.png">

While other concepts have plenty of connections:
<img width="1191" alt="Screenshot 2022-04-11 at 14 16 15" src="https://user-images.githubusercontent.com/2010517/162747925-4ad93ffb-8255-4fe3-aff8-51a8f1ed72bf.png">

I think this must be an issue with the GraphDB settings or import. Perhaps because the ontology being imported is quite large?
There are 354,125 OWL classes in the RDF file I attempted to import.

**Comment by kaicode** [comment]
I just tried reloading the RDF using the GraphDB "LoadRDF" tool on the command line but there was no change.
https://graphdb.ontotext.com/documentation/standard/loading-data-using-the-loadrdf-tool.html

On a mac I did this:
```
cd "/Applications/GraphDB Free.app/Contents/Java/bin"
./loadrdf -f -id snomed2 -m parallel ~/ontologies/rdf-xml-snomed.owl.zip
```

**Comment by riannella** [comment]
Hi @kaicode - in your comment above (Apr 11, 2022) you used:
`cd "/Applications/GraphDB Free.app/Contents/Java/bin"`

I get an error here...I don't seem to have the "Free.app" ??
(and how to "cd" to both app directories?)

Thanks...Renato

**Comment by kaicode** [comment]
Hi @riannella,
Another way to open the GraphDB bin folder on the command line is to start in Finder:
1. In Finder open the Applications folder
2. Right click on GraphDB Free (or whatever your version is called) and select "Show Package Contents"
<img width="580" alt="Screenshot 2023-11-29 at 07 37 11" src="https://github.com/IHTSDO/snomed-owl-toolkit/assets/2010517/9b49ffc1-7c38-42bb-9fbc-a952b50c8927">

3. Then go into Contents > Java >  bin
4. Once in the bin folder right click on "bin" at the bottom of the window and select "Open in Terminal"
<img width="954" alt="Screenshot 2023-11-29 at 07 38 39" src="https://github.com/IHTSDO/snomed-owl-toolkit/assets/2010517/b144f631-a9ba-444d-8b5e-9746da147b4d">

If you are not able to complete step 4 because the bar at the bottom of the window is not showing for you: first select "View" > "Show Path Bar" then complete step 4.

<img width="409" alt="Screenshot 2023-11-29 at 07 47 21" src="https://github.com/IHTSDO/snomed-owl-toolkit/assets/2010517/2a5d28fa-d43c-44a9-a9f4-fd0bf0e7ba93">

5. The Terminal will open in the correct folder. From here you can try the `./loadrdf -f -id snomed2 -m parallel ~/ontologies/rdf-xml-snomed.owl.zip` command. 
Note that `~/ontologies/rdf-xml-snomed.owl.zip` is the path to the snomed RDF zip file on my machine, you may have put yours somewhere else.

**Comment by riannella** [comment]
Thanks @kaicode ...
I just realised the name of your GDB app was "GraphDB Free.app" (space between the two words!)
I am using a newer/different version of GDB (the import is now called "importrdf".)
I have reported this to Ontotext and they acknowledge a bug...
Cheers - R

**Comment by VladimirAlexiev** [comment]
hi @kaicode !
The most likely reason is that these OWL expressions involve a bunch of blank nodes (owl:intersectionOf is an rdf:List, owl:Restriction also uses blank nodes...).
Perhaps you can play with vizGraph settings (SPARQL queries) to include such blank nodes.
