### ISSUE TITLE
Question about ontology classes and predicates

### ISSUE THREAD

**Issue by TereLaguinge** [IHTSDO/snomed-owl-toolkit#67]
Hi @kaicode ! I have a question about the ontology. I followed the steps described in question  [SNOMED CT conversion issues for GraphDB import](https://github.com/IHTSDO/snomed-owl-toolkit/issues/64#) but when I open the owl file in protege I'm just able to see this relations:

![image](https://user-images.githubusercontent.com/69465938/162738394-eab46bc9-4824-4ce9-98af-2e068f2140ec.png)

However, when comparing that to the ontology of SNOMED in bioportal: https://bioportal.bioontology.org/ontologies/SNOMEDCT

<img width="624" alt="image" src="https://user-images.githubusercontent.com/69465938/162441788-60e3e949-7604-4ffd-b580-b3eeaa9f568a.png">

I have other predicates like Has associated morphology or Has finding site that do not appear in the owl file. 

They seem to be here:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/69465938/162442032-726622d0-b0d2-4f65-a8b0-b25bae62d66c.png">

But they don´t seem to be recognized and when importing them in GraphDB, I just see the predicates: rdfs:label and skos:prefLabel, do you know how can I obtain them, if there's a way of obtaining them as triples?

Thanks in advance for your help! I put it in another issue since it's not related to the last one I posted.

**Comment by kaicode** [comment]
Hi @TereLaguinge, I see that I never responded to this issue... I tried importing into GraphDB but, like you, I couldn't figure out how to get the predicates to show up. Sorry not to be more help on this.
Please post back if you ever find the answer as it may be helpful for others.

**Comment by dinani65** [comment]
Hello @TereLaguinge 
I have the same problem, have u figured it out?

**Comment by kaicode** [comment]
If anyone knows what format is needed to import these attributes into GraphDB I may be able to help transform the SNOMED CT inferred relationships file. The OWL axioms only contain the triples before the classification process. The inferred relationships are a fuller set of information for querying.
I would need an example of one concept manually converted in order to script the rest. It would be best to pick a concept with more than one description, more than parent and more than one attribute.
