### ISSUE TITLE
Number of classes dropped after the transition

### ISSUE THREAD

**Issue by acadTags** [IHTSDO/snomed-owl-toolkit#71]
Thanks for publishing the tool. 

It seems that the number of classes drops after the transition to an owl ontology?

For example for `SNOMEDCT_US_20170301`, 
`332210` classes were kept after getting the `.owl` file, while there were originally `438406` unique concepts in the first column of  `SnomedCT_USEditionRF2_Production_20170301T120000/Full/Terminology/sct2_Concept_Full_US1000124_20170301.txt`. 

We found similar issues with another recent version of SNOMEDCT ontology as well. Did I miss something or is there anything to improve? 
Best regards, A

**Comment by acadTags** [comment]
> Only active concepts will be translated to OWL classes. I expect you will find that there are 332,210 concepts with an active value of 1 in the sct2_Concept_Full_US1000124_20170301.txt file.

Thanks. I think this is the main reason. By selecting the active value of 1 **with the most recent effectiveTime for each concept**, this resulted in 332,289 concepts, almost the same as 332,210.

**Comment by kaicode** [comment]
The remaining discrepancy is probably due to attributes. In SNOMED CT attributes (relationship types) are represented as concepts in the concept file, however in OWL these do not become Classes because they become either an ObjectProperty or a DataProperty. 
As a side note - the Snapshot files can be used to get the most recent state of each component, for example sct2_Concept_Snapshot_US1000124_20170301.txt. The Full files are only useful to look at past releases (history).

**Comment by acadTags** [comment]
> The remaining discrepancy is probably due to attributes. In SNOMED CT attributes (relationship types) are represented as concepts in the concept file, however in OWL these do not become Classes because they become either an ObjectProperty or a DataProperty. As a side note - the Snapshot files can be used to get the most recent state of each component, for example sct2_Concept_Snapshot_US1000124_20170301.txt. The Full files are only useful to look at past releases (history).

Thanks, this makes sense! Also now using the snapshot, I don't need to filter with effectiveTime.
