### ISSUE TITLE
Classification

### ISSUE THREAD

**Issue by alePelus** [IHTSDO/snomed-owl-toolkit#82]
Hello!

I am trying to classify the snomed spanish extension but I get this error:
![image](https://github.com/IHTSDO/snomed-owl-toolkit/assets/153510261/34ff6f4c-0e58-4d3c-8ea3-6d34c01e1ec6)
Should I do a previous transformation to my entry file?
this is the command that I used:
java --add-opens java.base/java.lang=ALL-UNNAMED -Xms4g -jar snomed-owl-toolkit-3.0.6-executable.jar -classify -rf2-snapshot-archives SnomedCT_SpainExtension_ES_PRODUCTION_20231201T120000Z.zip

Thank you in advance.

**Comment by kaicode** [comment]
Hi @alePelus,
When classifying an extension package it's necessary to provide an International Edition package as well.
See the command line example in this response: https://github.com/IHTSDO/snomed-owl-toolkit/issues/58#issuecomment-966267545

**Comment by kaicode** [comment]
The SNOMED CT International Edition download is available through the Member License and Distribution Service here: https://mlds.ihtsdotools.org/

**Comment by kaicode** [comment]
Update: For access to SNOMED CT resources in Spain I advise contacting the Spanish Ministry of Health. Spain do not use the MLDS service.
There is a relevant page here: https://www.sanidad.gob.es/areas/saludDigital/interoperabilidadSemantica/home.htm

**Comment by alePelus** [comment]
Thank you, it worked! I wonder if for classify the spanish drug extension I need the international edition as parameter too or not? 
And is there some type of manual in order to understand the result of the classification? because I need to identify if there is some incident when classifying but I don't understand completely the results. Thank you.

**Comment by kaicode** [comment]
There is no user manual for this project other than the readme file.

**Understanding classification results**
The classification process outputs a zip file with name format `classification-results-DATE.zip`
Within the zip there will be three files:
- `RF2/der2_sRefset_EquivalentConceptSimpleMapDelta_Classification_DATE.txt`
- `RF2/sct2_Relationship_Delta_Classification_DATE.txt`
- `RF2/sct2_RelationshipConcreteValues_Delta_Classification_DATE.txt`

The first line of each file is a header line that has the column names.

The EquivalentConcept file contains any concepts that the classification process has found to have equivalent logical definitions. Equivalent concepts are not recommended. If there are any concepts listed in this file then one of the concepts should be changed and the classification process run again to resolve the issue.

The Relationship and RelationshipConcreteValues files contain relationship changes that have been found. If these files do not contain changes it's because the input files are already classified and already contain all the necessary inferred relationships. Pay close attention to the active flag because new relationships will have active=1 whereas redundant relationships will have active=0. All of these changes should be saved into the new authoring cycle of the extension.

An RF2 delta archive of the content within the current authoring cycle can be input into the classification process using the `-rf2-authoring-delta-archive` parameter. When the content in the current authoring cycle contains all the classification changes then running classification again should result in no changes in the relationship output files.
